version: '3.3'

services:
  php-apache:
    container_name: site-fablab
    build:
      context: .
    volumes:
      - .:/var/www/html/
    #      - ./letsencrypt:/letsencrypt
    #      - ./traefik.http.yml:/etc/traefik/traefik.yml
    ports:
      - "8006:80"
    labels:
      - "traefik.enable=true"


      - "traefik.http.routers.fablab.rule=Host(`fablab-icam-toulouse.com`)"
      - "traefik.http.routers.fablab.entrypoints=web"
      - "traefik.http.routers.fablab.middlewares=test-redirectscheme"



      - "traefik.http.routers.fablab-secure.rule=Host(`fablab-icam-toulouse.com`)"
      - "traefik.http.routers.fablab-secure.entrypoints=websecure"
      - "traefik.http.routers.fablab-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.fablab-secure.middlewares=test-compress,test-errorpages,test-ratelimit"


      # Error Pages Middleware
      - "traefik.http.middlewares.test-errorpages.errors.status=400-599"
      - "traefik.http.middlewares.test-errorpages.errors.service=error"
      - "traefik.http.middlewares.test-errorpages.errors.query=/{status}.html"

      # Rate Limit Middleware
      - "traefik.http.middlewares.test-ratelimit.ratelimit.average=2"

      # Compress Middleware
      - "traefik.http.middlewares.test-compress.compress=true"

      # Redirect Scheme HTTP -> HTTPS
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
    #      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"


