version: '3.3'

services:
  php-apache:
    container_name: php-apache-fablab
    build:
      context: .
    volumes:
      - .:/var/www/html/
    ports:
      - "8006:80"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.php-apache.rule=Host(`fablab-icam-toulouse.com`)"
#      - "traefik.http.routers.php-apache.entrypoints=web"
#    networks:
#      - traefik-network


#  mysql:
#    image: mysql:5.7
#    container_name: mysql
#    env_file: ./env/mysql.env
#
#networks:
#  traefik-network:
#    external: true

#  phpmyadmin:
#    image: phpmyadmin:latest
#    container_name: phpmyadmin
#    env_file: ./env/pma.env
